name: CI (client)

on:
  push:
    branches: [ "main", "fix/*", "feature/*" ]
  pull_request:
    branches: [ "main", "fix/*", "feature/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.1.x

      - name: Install dependencies
        run: cd client && yarn install

      - name: Lint with ESLint
        run: cd client && yarn run lint

      - name: Check formatting with Prettier
        run: cd client && yarn check:format

      - name: Build app
        run: cd client && yarn run build

      - name: Run tests
        run: cd client && yarn test