name: CI (client)
on:
  push:
    branches: [ "main", "fix/*", "feature/*" ]
  pull_request:
    branches: [ "main", "fix/*", "feature/*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --prefix client

      - name: Lint with ESLint
        run: yarn run fix --prefix client

      - name: Check formatting with Prettier
        run: yarn check:format --prefix client

      - name: Build app
        run: yarn run build --prefix client

      - name: Run tests
        run: yarn test --prefix client