name: CI (client)

on:
  push:
    branches: [ "main", "fix/*", "feature/*" ]
  pull_request:
    branches: [ "main", "fix/*", "feature/*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4

#      - name: Set up Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 14.x
#
      - name: Install dependencies
        run: npm ci --prefix client
#
#      - name: Lint with ESLint
#        run: npm run lint --prefix client
#
#      - name: Check formatting with Prettier
#        run: npm run check-format
#
#      - name: Build app
#        run: npm run build --prefix client
#
#      - name: Run tests
#        run: npm test --prefix client


